In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

<class 'ModuleNotFoundError'>: No module named 'seaborn'

# 2. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**2.1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
a = np.arange(1, 21)
f = lambda n: 2**n/n
f(a)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
## your code
a = np.arange(0, 5)
f = lambda i:0.1**(3*i)*0.2**(4*i)
f(a).sum()

1.00000160000256

**2.3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [8]:
## your code
np.fromfunction(lambda i, j: (i+j+1)%2, (8, 8))

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**2.4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [9]:
X = np.random.random((10, 10))

## your code
import math
X = np.random.random((5, 2))

def cart_to_polar(a):
    x, y = a
    return (x**2+y**2)**(1/2), math.atan(y/x)

np.apply_along_axis(cart_to_polar, 1, X)

array([[1.01445699, 0.73417583],
       [0.9799461 , 0.58626665],
       [0.68581331, 0.85508826],
       [0.26979537, 0.23445045],
       [0.58194205, 0.27543465]])

**2.5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [12]:
X = np.random.random((10, 10))
coords = (np.argmax(X)//10, np.argmax(X)%10)
coords

(4, 1)

**2.6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [16]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

distances = np.linalg.norm(X - y, ord=2, axis=1)
print(f'{X[np.argmin(distances)]}')

[0.53320148 0.89341819]


**2.7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [17]:
## your code
def f(x):
    if x < 0:
        return x**2 + 2*x + 6
    elif 0 <= x <= 2:
        return x+6
    else:
        return x**2+4*x-4
    
np.vectorize(f)(np.arange(-3, 4))

array([ 9,  6,  5,  6,  7,  8, 17])

**2.8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [19]:
X = np.random.random((10, 10))
np.mean(X - np.mean(X)), (X - np.mean(X))

(-1.0824674490095276e-16,
 array([[-0.14947366,  0.00104874,  0.02350351, -0.40176873,  0.26952797,
          0.22190148,  0.48020648,  0.10386634,  0.33113096,  0.29768307],
        [-0.2413309 ,  0.40128691,  0.49551868,  0.20272051,  0.04541393,
          0.32776639,  0.37273032, -0.45716851, -0.07871517,  0.04982986],
        [ 0.02362073,  0.07773795, -0.07788279, -0.45081689,  0.1933101 ,
         -0.28994346, -0.18304213,  0.51111684, -0.47555992,  0.41760493],
        [-0.34977987,  0.3113157 ,  0.39220034,  0.07386317, -0.3153007 ,
         -0.2461182 , -0.14636504, -0.41912002, -0.32883636,  0.12265555],
        [ 0.03564517,  0.10456551, -0.18325461,  0.16034374,  0.16209122,
         -0.20328032,  0.00102734,  0.27234815, -0.20439071, -0.25015125],
        [-0.01811255, -0.16866009,  0.18132701, -0.41138353,  0.49739323,
         -0.34560601, -0.11539873,  0.10456666, -0.16745055,  0.21042582],
        [-0.38137311, -0.06085469,  0.06123704, -0.22663969, -0.41245954,
      

**2.9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [20]:
X = np.random.normal(loc=5, scale=2., size=1000)

np.mean(X), np.var(X)

(4.926561781151084, 3.9585871626093603)

**2.10.** Создать матрицу (NB. БЕЗ ЦИКЛОВ И ИЗМЕНЕНИЯ ОТДЕЛЬНЫХ ЭЛЕМЕНТОВ):

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [21]:
## your code
np.fromfunction(lambda i, j: (i+j)%5, (5, 5))

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**2.11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 0, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [22]:
## your code
def sample(x, c):
    vec = np.array(x)
    rand_vec = np.random.rand(c)*np.sum(vec)
    cumsum = np.transpose([np.cumsum(vec)])
    return np.argmax((rand_vec < cumsum).T, axis=1)
sample([50, 3, 1, 7, 20], 5) 

array([4, 3, 0, 1, 0], dtype=int32)